
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "calculeServiceService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8084/CalculeService?wsdl")
public class CalculeServiceService
    extends Service
{

    private final static URL CALCULESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULESERVICESERVICE_EXCEPTION;
    private final static QName CALCULESERVICESERVICE_QNAME = new QName("http://webservice/", "calculeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/CalculeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULESERVICESERVICE_WSDL_LOCATION = url;
        CALCULESERVICESERVICE_EXCEPTION = e;
    }

    public CalculeServiceService() {
        super(__getWsdlLocation(), CALCULESERVICESERVICE_QNAME);
    }

    public CalculeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULESERVICESERVICE_QNAME, features);
    }

    public CalculeServiceService(URL wsdlLocation) {
        super(wsdlLocation, CALCULESERVICESERVICE_QNAME);
    }

    public CalculeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULESERVICESERVICE_QNAME, features);
    }

    public CalculeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculeService
     */
    @WebEndpoint(name = "calculeServicePort")
    public CalculeService getCalculeServicePort() {
        return super.getPort(new QName("http://webservice/", "calculeServicePort"), CalculeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculeService
     */
    @WebEndpoint(name = "calculeServicePort")
    public CalculeService getCalculeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "calculeServicePort"), CalculeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULESERVICESERVICE_EXCEPTION!= null) {
            throw CALCULESERVICESERVICE_EXCEPTION;
        }
        return CALCULESERVICESERVICE_WSDL_LOCATION;
    }

}
