
package mypackage;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "calculeService", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculeService {


    /**
     * 
     * @param number1
     * @param number2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplicationTwoNumber", targetNamespace = "http://webservice/", className = "mypackage.MultiplicationTwoNumber")
    @ResponseWrapper(localName = "multiplicationTwoNumberResponse", targetNamespace = "http://webservice/", className = "mypackage.MultiplicationTwoNumberResponse")
    @Action(input = "http://webservice/calculeService/multiplicationTwoNumberRequest", output = "http://webservice/calculeService/multiplicationTwoNumberResponse")
    public int multiplicationTwoNumber(
        @WebParam(name = "number1", targetNamespace = "")
        int number1,
        @WebParam(name = "number2", targetNamespace = "")
        int number2);

    /**
     * 
     * @param number1
     * @param number2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divisionTwoNumber", targetNamespace = "http://webservice/", className = "mypackage.DivisionTwoNumber")
    @ResponseWrapper(localName = "divisionTwoNumberResponse", targetNamespace = "http://webservice/", className = "mypackage.DivisionTwoNumberResponse")
    @Action(input = "http://webservice/calculeService/divisionTwoNumberRequest", output = "http://webservice/calculeService/divisionTwoNumberResponse")
    public double divisionTwoNumber(
        @WebParam(name = "number1", targetNamespace = "")
        int number1,
        @WebParam(name = "number2", targetNamespace = "")
        int number2);

    /**
     * 
     * @param number1
     * @param number2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soustractionTwoNumber", targetNamespace = "http://webservice/", className = "mypackage.SoustractionTwoNumber")
    @ResponseWrapper(localName = "soustractionTwoNumberResponse", targetNamespace = "http://webservice/", className = "mypackage.SoustractionTwoNumberResponse")
    @Action(input = "http://webservice/calculeService/soustractionTwoNumberRequest", output = "http://webservice/calculeService/soustractionTwoNumberResponse")
    public int soustractionTwoNumber(
        @WebParam(name = "number1", targetNamespace = "")
        int number1,
        @WebParam(name = "number2", targetNamespace = "")
        int number2);

    /**
     * 
     * @param number1
     * @param number2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sommeTwoNumber", targetNamespace = "http://webservice/", className = "mypackage.SommeTwoNumber")
    @ResponseWrapper(localName = "sommeTwoNumberResponse", targetNamespace = "http://webservice/", className = "mypackage.SommeTwoNumberResponse")
    @Action(input = "http://webservice/calculeService/sommeTwoNumberRequest", output = "http://webservice/calculeService/sommeTwoNumberResponse")
    public int sommeTwoNumber(
        @WebParam(name = "number1", targetNamespace = "")
        int number1,
        @WebParam(name = "number2", targetNamespace = "")
        int number2);

}
